import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import React from "react";

import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';

const poppinsSans = Poppins({
  variable: "--font-poppins-sans",
  weight: ["400", "700"],
  subsets: ["latin"],
  style: ["normal", "italic"]
});

export const metadata: Metadata = {
  title: "BookRead",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={poppinsSans.className} >
        {children}
      </body>
    </html>
  );
}
